const keysRU = [
  // Row 1
  {value: 'ё', altValue: 'Ё', code: '192', row: 1},
  {value: '1', altValue: '!', code: '49', row: 1},
  {value: '2', altValue: '"', code: '50', row: 1},
  {value: '3', altValue: '№', code: '51', row: 1},
  {value: '4', altValue: ';', code: '52', row: 1},
  {value: '5', altValue: '%', code: '53', row: 1},
  {value: '6', altValue: ':', code: '54', row: 1},
  {value: '7', altValue: '?', code: '55', row: 1},
  {value: '8', altValue: '*', code: '56', row: 1},
  {value: '9', altValue: '(', code: '57', row: 1},
  {value: '0', altValue: ')', code: '48', row: 1},
  {value: '-', altValue: '_', code: '189', row: 1},
  {value: '=', altValue: '+', code: '187', row: 1},
  {value: 'Backspace', altValue: 'Backspace', code: '8', keycode: 'Backspace', row: 1},
  // Row 2
  {value: 'Tab', altValue: 'Tab', code: '9', keycode: 'Tab', row: 2},
  {value: 'й', altValue: 'Й', code: '81', row: 2},
  {value: 'ц', altValue: 'Ц', code: '87', row: 2},
  {value: 'у', altValue: 'У', code: '69', row: 2},
  {value: 'к', altValue: 'К', code: '82', row: 2},
  {value: 'е', altValue: 'Е', code: '84', row: 2},
  {value: 'н', altValue: 'Н', code: '89', row: 2},
  {value: 'г', altValue: 'Г', code: '85', row: 2},
  {value: 'ш', altValue: 'Ш', code: '73', row: 2},
  {value: 'щ', altValue: 'Щ', code: '79', row: 2},
  {value: 'з', altValue: 'З', code: '80', row: 2},
  {value: 'х', altValue: 'Х', code: '219', row: 2},
  {value: 'ъ', altValue: 'Ъ', code: '221', row: 2},
  {value: '\\', altValue: '/', code: '220', row: 2},
  {value: 'Del', altValue: 'Del', code:'46', keycode: 'Delete', row: 2},
  // Row 3
  {value: 'CapsLock', altValue: 'CapsLock', code: '20', keycode: 'CapsLock', row: 3},
  {value: 'ф', altValue: 'Ф', code: '65', row: 3},
  {value: 'ы', altValue: 'Ы', code: '83', row: 3},
  {value: 'в', altValue: 'В', code: '68', row: 3},
  {value: 'а', altValue: 'А', code: '70', row: 3},
  {value: 'п', altValue: 'П', code: '71', row: 3},
  {value: 'р', altValue: 'Р', code: '72', row: 3},
  {value: 'о', altValue: 'О', code: '74', row: 3},
  {value: 'л', altValue: 'Л', code: '75', row: 3},
  {value: 'д', altValue: 'Д', code: '76', row: 3},
  {value: 'ж', altValue: 'Ж', code: '186', row: 3},
  {value: 'э', altValue: 'Э', code: '222', row: 3},
  {value: 'Enter', altValue: 'Enter', code: '13', keycode: 'Enter', row: 3},
  // Row 4
  {value: 'Shift', altValue: 'Shift', code: '16', keycode: 'ShiftLeft', row: 4},
  {value: 'я', altValue: 'Я', code: '90', row: 4},
  {value: 'ч', altValue: 'Ч', code: '88', row: 4},
  {value: 'с', altValue: 'С', code: '67', row: 4},
  {value: 'м', altValue: 'М', code: '86', row: 4},
  {value: 'и', altValue: 'И', code: '66', row: 4},
  {value: 'т', altValue: 'Т', code: '78', row: 4},
  {value: 'ь', altValue: 'Ь', code: '77', row: 4},
  {value: 'ь', altValue: 'Ь', code: '77', row: 4},
  {value: 'б', altValue: 'Б', code: '188', row: 4},
  {value: 'ю', altValue: 'Ю', code: '190', row: 4},
  {value: '.', altValue: ',', code: '191', row: 4},
  {value: '▲', altValue: '▲', code: '38', keycode: 'ArrowUp', row: 4},
  {value: 'Shift', altValue: 'Shift', code: '16', keycode: 'ShiftRight', row: 4},
  // Row 5
  {value: 'Ctrl', altValue: 'Ctrl', code: '17', keycode: 'ControlLeft', row: 5},
  {value: 'Alt', altValue: 'Alt', code: '18', keycode: 'AltLeft', row: 5},
  {value: 'Space', altValue: 'Space', code: '32', keycode: 'Space', row: 5},  
  {value: '◄', altValue: '◄', code: '37', keycode: 'ArrowLeft', row: 5},
  {value: '▼', altValue: '▼', code: '40', keycode: 'ArrowDown', row: 5},
  {value: '►', altValue: '►', code: '39', keycode: 'ArrowRight', row: 5},
  {value: 'Ctrl', altValue: 'Ctrl', code: '17', keycode: 'ControlRight', row: 5},
  {value: 'Alt', altValue: 'Alt', code: '18', keycode: 'AltRight', row: 5}
]


export {keysRU};