const keysEN = [
  // Row 1
  {value: '`', altValue: '~', code: '192', row: 1},
  {value: '1', altValue: '!', code: '49', row: 1},
  {value: '2', altValue: '@', code: '50', row: 1},
  {value: '3', altValue: '#', code: '51', row: 1},
  {value: '4', altValue: '$', code: '52', row: 1},
  {value: '5', altValue: '%', code: '53', row: 1},
  {value: '6', altValue: '^', code: '54', row: 1},
  {value: '7', altValue: '&', code: '55', row: 1},
  {value: '8', altValue: '*', code: '56', row: 1},
  {value: '9', altValue: '(', code: '57', row: 1},
  {value: '0', altValue: ')', code: '48', row: 1},
  {value: '-', altValue: '_', code: '189', row: 1},
  {value: '=', altValue: '+', code: '187', row: 1},
  {value: 'Backspace', altValue: 'Backspace', code: '8', keycode: 'Backspace', row: 1},
  // Row 2
  {value: 'Tab', altValue: 'Tab', code: '9', keycode: 'Tab', row: 2},
  {value: 'q', altValue: 'Q', code: '81', row: 2},
  {value: 'w', altValue: 'W', code: '87', row: 2},
  {value: 'e', altValue: 'E', code: '69', row: 2},
  {value: 'r', altValue: 'R', code: '82', row: 2},
  {value: 't', altValue: 'T', code: '84', row: 2},
  {value: 'y', altValue: 'Y', code: '89', row: 2},
  {value: 'u', altValue: 'U', code: '85', row: 2},
  {value: 'i', altValue: 'I', code: '73', row: 2},
  {value: 'o', altValue: 'O', code: '79', row: 2},
  {value: 'p', altValue: 'P', code: '80', row: 2},
  {value: '[', altValue: '{', code: '219', row: 2},
  {value: ']', altValue: '}', code: '221', row: 2},
  {value: '\\', altValue: '|', code: '220', row: 2},
  {value: 'Del', altValue: 'Del', code:'46', keycode: 'Delete', row: 2},
  // Row 3
  {value: 'CapsLock', altValue: 'CapsLock', code: '20', keycode: 'CapsLock', row: 3},
  {value: 'a', altValue: 'A', code: '65', row: 3},
  {value: 's', altValue: 'S', code: '83', row: 3},
  {value: 'd', altValue: 'D', code: '68', row: 3},
  {value: 'f', altValue: 'F', code: '70', row: 3},
  {value: 'g', altValue: 'G', code: '71', row: 3},
  {value: 'h', altValue: 'H', code: '72', row: 3},
  {value: 'j', altValue: 'J', code: '74', row: 3},
  {value: 'k', altValue: 'K', code: '75', row: 3},
  {value: 'l', altValue: 'L', code: '76', row: 3},
  {value: ';', altValue: ':', code: '186', row: 3},
  {value: '\'', altValue: '"', code: '222', row: 3},
  {value: 'Enter', altValue: 'Enter', code: '13', keycode: 'Enter', row: 3},
  // Row 4
  {value: 'Shift', altValue: 'Shift', code: '16', keycode: 'ShiftLeft', row: 4},
  {value: 'z', altValue: 'Z', code: '90', row: 4},
  {value: 'x', altValue: 'X', code: '88', row: 4},
  {value: 'c', altValue: 'C', code: '67', row: 4},
  {value: 'v', altValue: 'V', code: '86', row: 4},
  {value: 'b', altValue: 'B', code: '66', row: 4},
  {value: 'n', altValue: 'N', code: '78', row: 4},
  {value: 'm', altValue: 'M', code: '77', row: 4},
  {value: 'm', altValue: 'M', code: '77', row: 4},
  {value: ',', altValue: '<', code: '188', row: 4},
  {value: '.', altValue: '>', code: '190', row: 4},
  {value: '/', altValue: '?', code: '191', row: 4},
  {value: '▲', altValue: '▲', code: '38', keycode: 'ArrowUp', row: 4},
  {value: 'Shift', altValue: 'Shift', code: '16', keycode: 'ShiftRight', row: 4},
  // Row 5
  {value: 'Ctrl', altValue: 'Ctrl', code: '17', keycode: 'ControlLeft', row: 5},
  {value: 'Alt', altValue: 'Alt', code: '18', keycode: 'AltLeft', row: 5},
  {value: 'Space', altValue: 'Space', code: '32', keycode: 'Space', row: 5},  
  {value: '◄', altValue: '◄', code: '37', keycode: 'ArrowLeft', row: 5},
  {value: '▼', altValue: '▼', code: '40', keycode: 'ArrowDown', row: 5},
  {value: '►', altValue: '►', code: '39', keycode: 'ArrowRight', row: 5},
  {value: 'Ctrl', altValue: 'Ctrl', code: '17', keycode: 'ControlRight', row: 5},
  {value: 'Alt', altValue: 'Alt', code: '18', keycode: 'AltRight', row: 5}
]


export {keysEN};