const keysEN = [
  // Row 1
  {value: '`', altValue: '~', code: 'Backquote', row: 1},
  {value: '1', altValue: '!', code: 'Digit1', row: 1},
  {value: '2', altValue: '@', code: 'Digit2', row: 1},
  {value: '3', altValue: '#', code: 'Digit3', row: 1},
  {value: '4', altValue: '$', code: 'Digit4', row: 1},
  {value: '5', altValue: '%', code: 'Digit5', row: 1},
  {value: '6', altValue: '^', code: 'Digit6', row: 1},
  {value: '7', altValue: '&', code: 'Digit7', row: 1},
  {value: '8', altValue: '*', code: 'Digit8', row: 1},
  {value: '9', altValue: '(', code: 'Digit9', row: 1},
  {value: '0', altValue: ')', code: 'Digit0', row: 1},
  {value: '-', altValue: '_', code: 'Minus', row: 1},
  {value: '=', altValue: '+', code: 'Equal', row: 1},
  {value: 'Backspace', altValue: 'Backspace', code: 'Backspace', row: 1},
  // Row 2
  {value: 'Tab', altValue: 'Tab', code: 'Tab', row: 2},
  {value: 'q', altValue: 'Q', code: 'KeyQ', row: 2},
  {value: 'w', altValue: 'W', code: 'KeyW', row: 2},
  {value: 'e', altValue: 'E', code: 'KeyE', row: 2},
  {value: 'r', altValue: 'R', code: 'KeyR', row: 2},
  {value: 't', altValue: 'T', code: 'KeyT', row: 2},
  {value: 'y', altValue: 'Y', code: 'KeyY', row: 2},
  {value: 'u', altValue: 'U', code: 'KeyU', row: 2},
  {value: 'i', altValue: 'I', code: 'KeyI', row: 2},
  {value: 'o', altValue: 'O', code: 'KeyO', row: 2},
  {value: 'p', altValue: 'P', code: 'KeyP', row: 2},
  {value: '[', altValue: '{', code: 'BracketLeft', row: 2},
  {value: ']', altValue: '}', code: 'BracketRight', row: 2},
  {value: '\\', altValue: '|', code: 'Backslash', row: 2},
  {value: 'Del', altValue: 'Del', code: 'Delete', row: 2},
  // Row 3
  {value: 'CapsLock', altValue: 'CapsLock', code: 'CapsLock', row: 3},
  {value: 'a', altValue: 'A', code: 'KeyA', row: 3},
  {value: 's', altValue: 'S', code: 'KeyS', row: 3},
  {value: 'd', altValue: 'D', code: 'KeyD', row: 3},
  {value: 'f', altValue: 'F', code: 'KeyF', row: 3},
  {value: 'g', altValue: 'G', code: 'KeyG', row: 3},
  {value: 'h', altValue: 'H', code: 'KeyH', row: 3},
  {value: 'j', altValue: 'J', code: 'KeyJ', row: 3},
  {value: 'k', altValue: 'K', code: 'KeyK', row: 3},
  {value: 'l', altValue: 'L', code: 'KeyL', row: 3},
  {value: ';', altValue: ':', code: 'Semicolon', row: 3},
  {value: '\'', altValue: '"', code: 'Quote', row: 3},
  {value: 'Enter', altValue: 'Enter', code: 'Enter', row: 3},
  // Row 4
  {value: 'Shift', altValue: 'Shift', code: 'ShiftLeft', row: 4},
  {value: 'z', altValue: 'Z', code: 'KeyZ', row: 4},
  {value: 'x', altValue: 'X', code: 'KeyX', row: 4},
  {value: 'c', altValue: 'C', code: 'KeyC', row: 4},
  {value: 'v', altValue: 'V', code: 'KeyV', row: 4},
  {value: 'b', altValue: 'B', code: 'KeyB', row: 4},
  {value: 'n', altValue: 'N', code: 'KeyN', row: 4},
  {value: 'm', altValue: 'M', code: 'KeyM', row: 4},
  {value: 'm', altValue: 'M', code: 'KeyM', row: 4},
  {value: ',', altValue: '<', code: 'Comma', row: 4},
  {value: '.', altValue: '>', code: 'Period', row: 4},
  {value: '/', altValue: '?', code: 'Slash', row: 4},
  {value: '▲', altValue: '▲', code: 'ArrowUp', row: 4},
  {value: 'Shift', altValue: 'Shift', code: 'ShiftRight', row: 4},
  // Row 5
  {value: 'Ctrl', altValue: 'Ctrl', code: 'ControlLeft', row: 5},
  {value: 'Alt', altValue: 'Alt', code: 'Altleft', row: 5},
  {value: 'Space', altValue: 'Space', code: 'Space', row: 5},  
  {value: '◄', altValue: '◄', code: 'ArrowLeft', row: 5},
  {value: '▼', altValue: '▼', code: 'ArrowDown', row: 5},
  {value: '►', altValue: '►', code: 'ArrowRight', row: 5},
  {value: 'Ctrl', altValue: 'Ctrl', code: 'ControlRight', row: 5},
  {value: 'Alt', altValue: 'Alt', code: 'AltRight', row: 5}
]


export {keysEN};